name: Flutter build apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3

      - name: Flutter einrichten
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: APK erstellen
        run: flutter build apk --release

      - name: APK-Artefakt hochladen
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
